/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as klTokenSol from "./KlToken.sol";
export type { klTokenSol };
import type * as redApp1Sol from "./RedApp1.sol";
export type { redApp1Sol };
export type { Counter } from "./Counter";
export type { CourseMarketplace } from "./CourseMarketplace";
export type { CoursePurchase } from "./CoursePurchase";
export type { KLExchange } from "./KLExchange";
export type { KLchange } from "./KLchange";
export type { RedApp } from "./RedApp";
export type { RedPacket } from "./RedPacket";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export { CourseMarketplace__factory } from "./factories/CourseMarketplace__factory";
export { CoursePurchase__factory } from "./factories/CoursePurchase__factory";
export { KLchange__factory } from "./factories/KLchange__factory";
export { KLExchange__factory } from "./factories/KLExchange__factory";
export type { MyToken } from "./KlToken.sol/MyToken";
export { MyToken__factory } from "./factories/KlToken.sol/MyToken__factory";
export { RedApp__factory } from "./factories/RedApp__factory";
export { RedPacket__factory } from "./factories/RedPacket__factory";
